namespace Lich {

    export enum AnimationSetKey {
        METEOR_ANIMATION_KEY,
        FIREBALL_ANIMATION_KEY,
        LICH_ANIMATION_KEY,
        CORPSE_ANIMATION_KEY,
        HELLHOUND_ANIMATION_KEY,
        ICEBOLT_ANIMATION_KEY,
        CHICKEN_ANIMATION_KEY,
        BUNNY_ANIMATION_KEY,
        CHICKEN_BOSS_ANIMATION_KEY,
        VALENTIMON_ANIMATION_KEY,
        LOVELETTER_ANIMATION_KEY,
        LOVEARROW_ANIMATION_KEY,
        CUPID_ANIMATION_KEY
    }

    export enum AnimationKey {
        // Hero
        ANM_HERO_IDLE_KEY,
        ANM_HERO_BREATH_KEY,
        ANM_HERO_WALKR_KEY,
        ANM_HERO_WALKL_KEY,
        ANM_HERO_JUMP_KEY,
        ANM_HERO_MIDAIR_KEY,
        ANM_HERO_FALL_KEY,
        ANM_HERO_JUMPR_KEY,
        ANM_HERO_JUMPL_KEY,
        ANM_HERO_DIE_KEY,
        ANM_HERO_DEAD_KEY,
        ANM_HERO_TELEPORT_KEY,
        ANM_HERO_CLIMB_KEY,
        // Bunny
        ANM_BUNNY_EATL_KEY,
        ANM_BUNNY_IDLEL_KEY,
        ANM_BUNNY_JUMPL_KEY,
        ANM_BUNNY_WALKL_KEY,
        ANM_BUNNY_WALKR_KEY,
        ANM_BUNNY_JUMPR_KEY,
        ANM_BUNNY_IDLER_KEY,
        ANM_BUNNY_EATR_KEY,
        ANM_BUNNY_DIE_KEY,
        // Chicken
        ANM_CHICKEN_EATL_KEY,
        ANM_CHICKEN_IDLEL_KEY,
        ANM_CHICKEN_JUMPL_KEY,
        ANM_CHICKEN_WALKL_KEY,
        ANM_CHICKEN_WALKR_KEY,
        ANM_CHICKEN_JUMPR_KEY,
        ANM_CHICKEN_IDLER_KEY,
        ANM_CHICKEN_EATR_KEY,
        ANM_CHICKEN_DIE_KEY,
        // Redskull
        ANM_REDSKULL_IDLE_KEY,
        ANM_REDSKULL_BREATH_KEY,
        ANM_REDSKULL_WALKR_KEY,
        ANM_REDSKULL_WALKL_KEY,
        ANM_REDSKULL_JUMP_KEY,
        ANM_REDSKULL_MIDAIR_KEY,
        ANM_REDSKULL_FALL_KEY,
        ANM_REDSKULL_JUMPR_KEY,
        ANM_REDSKULL_JUMPL_KEY,
        ANM_REDSKULL_DIE_KEY,
        ANM_REDSKULL_DEAD_KEY,
        ANM_REDSKULL_TELEPORT_KEY,
        ANM_REDSKULL_CLIMB_KEY,
        // Murhun
        ANM_MURHUN_IDLE_KEY,
        ANM_MURHUN_ATTACK_KEY,
        // Hellhound
        ANM_HELLHOUND_IDLE_KEY,
        ANM_HELLHOUND_WALKR_KEY,
        ANM_HELLHOUND_WALKL_KEY,
        ANM_HELLHOUND_JUMPR_KEY,
        ANM_HELLHOUND_JUMPL_KEY,
        // Cupid
        ANM_CUPID_IDLE_KEY,
        ANM_CUPID_ATTACK_KEY,
        ANM_CUPID_HIT_KEY,
        ANM_CUPID_DIE_KEY,
        ANM_CUPID_EXPLODE_KEY,
        ANM_CUPID_DEAD_KEY,
        // Valentimon
        ANM_VALENTIMON_IDLE_KEY,
        ANM_VALENTIMON_ATTACK_KEY,
        ANM_VALENTIMON_DIE_KEY,
        ANM_VALENTIMON_DEAD_KEY,
        // Projectiles
        ANM_BULLET_FLY_KEY,
        ANM_BULLET_HIT_KEY,
        ANM_BULLET_DONE_KEY,
    }

}