namespace Lich {
    let tsf = ThemeWatch.getThemeSuffix();
    export let MAP_OBJECT_PATHS: Array<[string, MapObjectKey]> = [
        ["images/parts/berry" + tsf + ".png", MapObjectKey.MAP_BERRY_KEY],
        ["images/parts/bush" + tsf + ".png", MapObjectKey.MAP_BUSH_KEY],
        ["images/parts/bush2" + tsf + ".png", MapObjectKey.MAP_BUSH2_KEY],
        ["images/parts/grass" + tsf + ".png", MapObjectKey.MAP_GRASS1_KEY],
        ["images/parts/grass2" + tsf + ".png", MapObjectKey.MAP_GRASS2_KEY],
        ["images/parts/grass3" + tsf + ".png", MapObjectKey.MAP_GRASS3_KEY],
        ["images/parts/grave.png", MapObjectKey.MAP_GRAVE_KEY],
        ["images/parts/mushroom.png", MapObjectKey.MAP_MUSHROOM_KEY],
        ["images/parts/mushroom2.png", MapObjectKey.MAP_MUSHROOM2_KEY],
        ["images/parts/mushroom3.png", MapObjectKey.MAP_MUSHROOM3_KEY],
        ["images/parts/plant" + tsf + ".png", MapObjectKey.MAP_RED_PLANT_KEY],
        ["images/parts/plant2" + tsf + ".png", MapObjectKey.MAP_MAGENTA_PLANT_KEY],
        ["images/parts/plant3" + tsf + ".png", MapObjectKey.MAP_CYAN_PLANT_KEY],
        ["images/parts/plant4" + tsf + ".png", MapObjectKey.MAP_YELLOW_PLANT_KEY],
        ["images/parts/tree5" + tsf + ".png", MapObjectKey.MAP_TREE_KEY],
        ["images/parts/tree6" + tsf + ".png", MapObjectKey.MAP_TREE2_KEY],
        ["images/parts/tree3" + tsf + ".png", MapObjectKey.MAP_TREE3_KEY],
        ["images/parts/tree4" + tsf + ".png", MapObjectKey.MAP_TREE4_KEY],
        ["images/parts/florite.png", MapObjectKey.MAP_FLORITE_KEY],
        ["images/parts/campfire.png", MapObjectKey.MAP_CAMPFIRE_KEY],
        ["images/parts/door_closed.png", MapObjectKey.MAP_DOOR_CLOSED_KEY],
        ["images/parts/door_open.png", MapObjectKey.MAP_DOOR_OPEN_KEY],
        ["images/parts/door_closed2.png", MapObjectKey.MAP_DOOR_CLOSED2_KEY],
        ["images/parts/door_open2.png", MapObjectKey.MAP_DOOR_OPEN2_KEY],
        ["images/parts/torch.png", MapObjectKey.MAP_TORCH_KEY],
        ["images/parts/anvil.png", MapObjectKey.MAP_ANVIL_KEY],
        ["images/parts/smelter.png", MapObjectKey.MAP_SMELTER_KEY],
        ["images/parts/iron_ingot.png", MapObjectKey.MAP_IRON_INGOT_KEY],
        ["images/parts/iron_fence.png", MapObjectKey.MAP_IRON_FENCE_KEY],
        ["images/parts/fireplace.png", MapObjectKey.MAP_FIREPLACE_KEY],
        ["images/parts/knight_statue.png", MapObjectKey.MAP_KNIGHT_STATUE_KEY],
        ["images/parts/banner.png", MapObjectKey.MAP_BANNER_KEY],
        ["images/parts/flower_pot.png", MapObjectKey.MAP_FLOWER_POT_KEY],
        ["images/parts/chandelier.png", MapObjectKey.MAP_CHANDELIER_KEY],
        ["images/parts/cauldron.png", MapObjectKey.MAP_CAULDRON_KEY],
        ["images/parts/red_flask.png", MapObjectKey.MAP_RED_FLASK_KEY],
        ["images/parts/chicken_meat.png", MapObjectKey.MAP_CHICKEN_MEAT_KEY],
        ["images/parts/xmas_blue_bauble.png", MapObjectKey.MAP_XMAS_BLUE_BAUBLE_KEY],
        ["images/parts/xmas_green_bauble.png", MapObjectKey.MAP_XMAS_GREEN_BAUBLE_KEY],
        ["images/parts/xmas_purple_bauble.png", MapObjectKey.MAP_XMAS_PURPLE_BAUBLE_KEY],
        ["images/parts/xmas_red_bauble.png", MapObjectKey.MAP_XMAS_RED_BAUBLE_KEY],
        ["images/parts/xmas_yellow_bauble.png", MapObjectKey.MAP_XMAS_YELLOW_BAUBLE_KEY],
        ["images/parts/xmas_holly.png", MapObjectKey.MAP_XMAS_HOLLY_KEY],
        ["images/parts/xmas_chain.png", MapObjectKey.MAP_XMAS_CHAIN_KEY],
        ["images/parts/xmas_tree.png", MapObjectKey.MAP_XMAS_TREE_KEY],
        ["images/parts/advent_wreath.png", MapObjectKey.MAP_ADVENT_WREATH_KEY],
        ["images/parts/snowman.png", MapObjectKey.MAP_SNOWMAN_KEY],
        ["images/parts/wood_chair.png", MapObjectKey.MAP_WOOD_CHAIR_KEY],
        ["images/parts/wood_chair2.png", MapObjectKey.MAP_WOOD_CHAIR2_KEY],
        ["images/parts/wood_table.png", MapObjectKey.MAP_WOOD_TABLE_KEY],
        ["images/parts/gold_coins.png", MapObjectKey.MAP_GOLD_COINS_KEY],
        ["images/parts/gold_coins2.png", MapObjectKey.MAP_GOLD_COINS2_KEY],
        ["images/parts/silver_coins.png", MapObjectKey.MAP_SILVER_COINS_KEY],
        ["images/parts/gold_dishes.png", MapObjectKey.MAP_GOLD_DISHES_KEY],
        ["images/parts/gold_dishes2.png", MapObjectKey.MAP_GOLD_DISHES2_KEY],
        ["images/parts/gold_bowl.png", MapObjectKey.MAP_GOLD_BOWL_KEY],
        ["images/parts/skeleton_on_chair.png", MapObjectKey.MAP_SKELETON_ON_CHAIR_KEY],
        ["images/parts/dead_fireplace.png", MapObjectKey.MAP_DEAD_FIREPLACE_KEY],
        ["images/parts/dead_chandelier.png", MapObjectKey.MAP_DEAD_CHANDELIER_KEY],
        ["images/parts/wooden_chest.png", MapObjectKey.MAP_WOODEN_CHEST_KEY],
        ["images/parts/wooden_chest_gold.png", MapObjectKey.MAP_WOODEN_GOLD_CHEST_KEY],
        ["images/parts/armchair.png", MapObjectKey.MAP_ARMCHAIR_KEY],
        ["images/parts/books.png", MapObjectKey.MAP_BOOKS_KEY],
        ["images/parts/bookshelf.png", MapObjectKey.MAP_BOOKSHELF_KEY],
        ["images/parts/cabinet.png", MapObjectKey.MAP_CABINET_KEY],
        ["images/parts/candle.png", MapObjectKey.MAP_CANDLE_KEY],
        ["images/parts/portrait_valentimon.png", MapObjectKey.MAP_PORTRAIT_VALENTIMON_KEY]
    ];
}