namespace Lich {
    let tsf = ThemeWatch.getThemeSuffix();
    export let MAP_OBJECT_PATHS: Array<[string, MapObjectKey]> = [
        ["berry" + tsf, MapObjectKey.MAP_BERRY_KEY],
        ["bush" + tsf, MapObjectKey.MAP_BUSH_KEY],
        ["bush2" + tsf, MapObjectKey.MAP_BUSH2_KEY],
        ["grass" + tsf, MapObjectKey.MAP_GRASS1_KEY],
        ["grass2" + tsf, MapObjectKey.MAP_GRASS2_KEY],
        ["grass3" + tsf, MapObjectKey.MAP_GRASS3_KEY],
        ["grave", MapObjectKey.MAP_GRAVE_KEY],
        ["mushroom", MapObjectKey.MAP_MUSHROOM_KEY],
        ["mushroom2", MapObjectKey.MAP_MUSHROOM2_KEY],
        ["mushroom3", MapObjectKey.MAP_MUSHROOM3_KEY],
        ["plant" + tsf, MapObjectKey.MAP_RED_PLANT_KEY],
        ["plant2" + tsf, MapObjectKey.MAP_MAGENTA_PLANT_KEY],
        ["plant3" + tsf, MapObjectKey.MAP_CYAN_PLANT_KEY],
        ["plant4" + tsf, MapObjectKey.MAP_YELLOW_PLANT_KEY],
        ["tree5" + tsf, MapObjectKey.MAP_TREE_KEY],
        ["tree6" + tsf, MapObjectKey.MAP_TREE2_KEY],
        ["tree3" + tsf, MapObjectKey.MAP_TREE3_KEY],
        ["tree4" + tsf, MapObjectKey.MAP_TREE4_KEY],
        ["florite", MapObjectKey.MAP_FLORITE_KEY],
        ["campfire", MapObjectKey.MAP_CAMPFIRE_KEY],
        ["door_closed", MapObjectKey.MAP_DOOR_CLOSED_KEY],
        ["door_open", MapObjectKey.MAP_DOOR_OPEN_KEY],
        ["door_closed2", MapObjectKey.MAP_DOOR_CLOSED2_KEY],
        ["door_open2", MapObjectKey.MAP_DOOR_OPEN2_KEY],
        ["torch", MapObjectKey.MAP_TORCH_KEY],
        ["anvil", MapObjectKey.MAP_ANVIL_KEY],
        ["smelter", MapObjectKey.MAP_SMELTER_KEY],
        ["iron_ingot", MapObjectKey.MAP_IRON_INGOT_KEY],
        ["iron_fence", MapObjectKey.MAP_IRON_FENCE_KEY],
        ["fireplace", MapObjectKey.MAP_FIREPLACE_KEY],
        ["knight_statue", MapObjectKey.MAP_KNIGHT_STATUE_KEY],
        ["banner", MapObjectKey.MAP_BANNER_KEY],
        ["flower_pot", MapObjectKey.MAP_FLOWER_POT_KEY],
        ["chandelier", MapObjectKey.MAP_CHANDELIER_KEY],
        ["cauldron", MapObjectKey.MAP_CAULDRON_KEY],
        ["red_flask", MapObjectKey.MAP_RED_FLASK_KEY],
        ["chicken_meat", MapObjectKey.MAP_CHICKEN_MEAT_KEY],
        ["xmas_blue_bauble", MapObjectKey.MAP_XMAS_BLUE_BAUBLE_KEY],
        ["xmas_green_bauble", MapObjectKey.MAP_XMAS_GREEN_BAUBLE_KEY],
        ["xmas_purple_bauble", MapObjectKey.MAP_XMAS_PURPLE_BAUBLE_KEY],
        ["xmas_red_bauble", MapObjectKey.MAP_XMAS_RED_BAUBLE_KEY],
        ["xmas_yellow_bauble", MapObjectKey.MAP_XMAS_YELLOW_BAUBLE_KEY],
        ["xmas_holly", MapObjectKey.MAP_XMAS_HOLLY_KEY],
        ["xmas_chain", MapObjectKey.MAP_XMAS_CHAIN_KEY],
        ["xmas_tree", MapObjectKey.MAP_XMAS_TREE_KEY],
        ["advent_wreath", MapObjectKey.MAP_ADVENT_WREATH_KEY],
        ["snowman", MapObjectKey.MAP_SNOWMAN_KEY],
        ["wood_chair", MapObjectKey.MAP_WOOD_CHAIR_KEY],
        ["wood_chair2", MapObjectKey.MAP_WOOD_CHAIR2_KEY],
        ["wood_table", MapObjectKey.MAP_WOOD_TABLE_KEY],
        ["gold_coins", MapObjectKey.MAP_GOLD_COINS_KEY],
        ["gold_coins2", MapObjectKey.MAP_GOLD_COINS2_KEY],
        ["silver_coins", MapObjectKey.MAP_SILVER_COINS_KEY],
        ["gold_dishes", MapObjectKey.MAP_GOLD_DISHES_KEY],
        ["gold_dishes2", MapObjectKey.MAP_GOLD_DISHES2_KEY],
        ["gold_bowl", MapObjectKey.MAP_GOLD_BOWL_KEY],
        ["skeleton_on_chair", MapObjectKey.MAP_SKELETON_ON_CHAIR_KEY],
        ["dead_fireplace", MapObjectKey.MAP_DEAD_FIREPLACE_KEY],
        ["dead_chandelier", MapObjectKey.MAP_DEAD_CHANDELIER_KEY],
        ["wooden_chest", MapObjectKey.MAP_WOODEN_CHEST_KEY],
        ["wooden_chest_gold", MapObjectKey.MAP_WOODEN_GOLD_CHEST_KEY],
        ["armchair", MapObjectKey.MAP_ARMCHAIR_KEY],
        ["books", MapObjectKey.MAP_BOOKS_KEY],
        ["bookshelf", MapObjectKey.MAP_BOOKSHELF_KEY],
        ["cabinet", MapObjectKey.MAP_CABINET_KEY],
        ["candle", MapObjectKey.MAP_CANDLE_KEY],
        ["portrait_valentimon", MapObjectKey.MAP_PORTRAIT_VALENTIMON_KEY]
    ];
}