namespace Lich {
    export let SOUND_PATHS: Array<[string, SoundKey]> = [
        ["sound/fireball_cast.ogg", SoundKey.SND_FIREBALL_KEY],
        ["sound/pick.ogg", SoundKey.SND_PICK_KEY],
        ["sound/fireball_hit.ogg", SoundKey.SND_BURN_KEY],
        ["sound/bolt_cast.ogg", SoundKey.SND_BOLT_CAST_KEY],
        ["sound/place.ogg", SoundKey.SND_PLACE_KEY],
        ["sound/pick_axe1.ogg", SoundKey.SND_PICK_AXE_1_KEY],
        ["sound/pick_axe2.ogg", SoundKey.SND_PICK_AXE_2_KEY],
        ["sound/pick_axe3.ogg", SoundKey.SND_PICK_AXE_3_KEY],
        ["sound/bonecrack.ogg", SoundKey.SND_BONE_CRACK_KEY],
        ["sound/skeleton_die.ogg", SoundKey.SND_SKELETON_DIE_KEY],
        ["sound/spawn.ogg", SoundKey.SND_SPAWN_KEY],
        ["sound/door_open.ogg", SoundKey.SND_DOOR_OPEN_KEY],
        ["sound/door_close.ogg", SoundKey.SND_DOOR_CLOSE_KEY],
        ["sound/craft.ogg", SoundKey.SND_CRAFT_KEY],
        ["sound/click.ogg", SoundKey.SND_CLICK_KEY],
        ["sound/meteor_fall.ogg", SoundKey.SND_METEOR_FALL_KEY],
        ["sound/meteor_hit.ogg", SoundKey.SND_METEOR_HIT_KEY],
        ["sound/teleport.ogg", SoundKey.SND_TELEPORT_KEY],
        ["sound/ghoul_spawn.ogg", SoundKey.SND_GHOUL_SPAWN_KEY],
        ["sound/punch1.ogg", SoundKey.SND_PUNCH_1_KEY],
        ["sound/punch2.ogg", SoundKey.SND_PUNCH_2_KEY],
        ["sound/punch3.ogg", SoundKey.SND_PUNCH_3_KEY],
        ["sound/punch4.ogg", SoundKey.SND_PUNCH_4_KEY],
        ["sound/bone_crush.ogg", SoundKey.SND_SQUASHED_KEY],
        ["sound/chicken_hit1.ogg", SoundKey.SND_CHICKEN_HIT_1_KEY],
        ["sound/chicken_hit2.ogg", SoundKey.SND_CHICKEN_HIT_2_KEY],
        ["sound/chicken_hit3.ogg", SoundKey.SND_CHICKEN_HIT_3_KEY],
        ["sound/chicken_dead1.ogg", SoundKey.SND_CHICKEN_DEAD_1_KEY],
        ["sound/chicken_dead2.ogg", SoundKey.SND_CHICKEN_DEAD_2_KEY],
        ["sound/chicken_dead3.ogg", SoundKey.SND_CHICKEN_DEAD_3_KEY],
        ["sound/chicken_idle.ogg", SoundKey.SND_CHICKEN_IDLE_KEY],
        ["sound/chicken_boss_die.ogg", SoundKey.SND_CHICKEN_BOSS_DEAD_KEY],
        ["sound/chicken_boss_hit.ogg", SoundKey.SND_CHICKEN_BOSS_HIT_KEY],
        ["sound/chicken_boss_attack.ogg", SoundKey.SND_CHICKEN_BOSS_ATTACK_KEY]
    ]
}