namespace Lich {
    export let INVENTORY_PATHS: Array<[string, InventoryKey]> = [
        ["images/ui/inventory/inv_bones.png", InventoryKey.INV_BONES_KEY],
        ["images/ui/inventory/inv_berry.png", InventoryKey.INV_BERRY_KEY],
        ["images/ui/inventory/inv_mushroom.png", InventoryKey.INV_MUSHROOM_KEY],
        ["images/ui/inventory/inv_mushroom2.png", InventoryKey.INV_MUSHROOM2_KEY],
        ["images/ui/inventory/inv_mushroom3.png", InventoryKey.INV_MUSHROOM3_KEY],
        ["images/ui/inventory/inv_plant.png", InventoryKey.INV_PLANT_KEY],
        ["images/ui/inventory/inv_plant2.png", InventoryKey.INV_PLANT2_KEY],
        ["images/ui/inventory/inv_plant3.png", InventoryKey.INV_PLANT3_KEY],
        ["images/ui/inventory/inv_plant4.png", InventoryKey.INV_PLANT4_KEY],
        ["images/ui/inventory/inv_straw.png", InventoryKey.INV_STRAW_KEY],
        ["images/ui/inventory/inv_wood.png", InventoryKey.INV_WOOD_KEY],
        ["images/ui/inventory/inv_dirt.png", InventoryKey.INV_DIRT_KEY],
        ["images/ui/inventory/inv_krystals.png", InventoryKey.INV_KRYSTAL_KEY],
        ["images/ui/inventory/inv_florite.png", InventoryKey.INV_FLORITE_KEY],
        ["images/ui/inventory/inv_campfire.png", InventoryKey.INV_CAMPFIRE_KEY],
        ["images/ui/inventory/inv_door.png", InventoryKey.INV_DOOR_KEY],
        ["images/ui/inventory/inv_brick.png", InventoryKey.INV_BRICK_KEY],
        ["images/ui/inventory/inv_woodwall.png", InventoryKey.INV_WOODWALL_KEY],
        ["images/ui/inventory/inv_roof.png", InventoryKey.INV_ROOF_KEY],
        ["images/ui/inventory/inv_iron.png", InventoryKey.INV_IRON_KEY],
        ["images/ui/inventory/inv_coal.png", InventoryKey.INV_COAL_KEY],
        ["images/ui/inventory/inv_rock.png", InventoryKey.INV_ROCK_KEY],
        ["images/ui/inventory/inv_rock_brick.png", InventoryKey.INV_ROCK_BRICK_KEY],
        ["images/ui/inventory/inv_torch.png", InventoryKey.INV_TORCH_KEY],
        ["images/ui/inventory/inv_anvil.png", InventoryKey.INV_ANVIL_KEY],
        ["images/ui/inventory/inv_smelter.png", InventoryKey.INV_SMELTER_KEY],
        ["images/ui/inventory/inv_iron_ingot.png", InventoryKey.INV_IRON_INGOT_KEY],
        ["images/ui/inventory/inv_iron_fence.png", InventoryKey.INV_IRON_FENCE_KEY],
        ["images/ui/inventory/inv_iron_platform.png", InventoryKey.INV_IRON_PLATFORM_KEY],
        ["images/ui/inventory/inv_wood_platform.png", InventoryKey.INV_WOOD_PLATFORM_KEY],
        ["images/ui/inventory/inv_grave.png", InventoryKey.INV_GRAVE_KEY],
        ["images/ui/inventory/inv_wood_ladder.png", InventoryKey.INV_WOOD_LADDER_KEY],
        ["images/ui/inventory/inv_fireplace.png", InventoryKey.INV_FIREPLACE_KEY],
        ["images/ui/inventory/inv_roof_tl.png", InventoryKey.INV_ROOF_TL_KEY],
        ["images/ui/inventory/inv_roof_tr.png", InventoryKey.INV_ROOF_TR_KEY],
        ["images/ui/inventory/inv_rock_brick_tl.png", InventoryKey.INV_ROCK_BRICK_TL_KEY],
        ["images/ui/inventory/inv_rock_brick_tr.png", InventoryKey.INV_ROCK_BRICK_TR_KEY],
        ["images/ui/inventory/inv_rock_brick_bl.png", InventoryKey.INV_ROCK_BRICK_BL_KEY],
        ["images/ui/inventory/inv_rock_brick_br.png", InventoryKey.INV_ROCK_BRICK_BR_KEY],
        ["images/ui/inventory/inv_rock_brick_window.png", InventoryKey.INV_ROCK_BRICK_WINDOW_KEY],
        ["images/ui/inventory/inv_knight_statue.png", InventoryKey.INV_KNIGHT_STATUE_KEY],
        ["images/ui/inventory/inv_chain_ladder.png", InventoryKey.INV_CHAIN_LADDER_KEY]
    ]
}