namespace Lich {
    export let MAP_OBJECT_PATHS: Array<[string, MapObjectKey]> = [
        ["images/parts/berry.png", MapObjectKey.MAP_BERRY_KEY],
        ["images/parts/bush.png", MapObjectKey.MAP_BUSH_KEY],
        ["images/parts/bush2.png", MapObjectKey.MAP_BUSH2_KEY],
        ["images/parts/grass.png", MapObjectKey.MAP_GRASS_KEY],
        ["images/parts/grass2.png", MapObjectKey.MAP_GRASS2_KEY],
        ["images/parts/grass3.png", MapObjectKey.MAP_GRASS3_KEY],
        ["images/parts/grave.png", MapObjectKey.MAP_GRAVE_KEY],
        ["images/parts/mushroom.png", MapObjectKey.MAP_MUSHROOM_KEY],
        ["images/parts/mushroom2.png", MapObjectKey.MAP_MUSHROOM2_KEY],
        ["images/parts/mushroom3.png", MapObjectKey.MAP_MUSHROOM3_KEY],
        ["images/parts/plant.png", MapObjectKey.MAP_PLANT_KEY],
        ["images/parts/plant2.png", MapObjectKey.MAP_PLANT2_KEY],
        ["images/parts/plant3.png", MapObjectKey.MAP_PLANT3_KEY],
        ["images/parts/plant4.png", MapObjectKey.MAP_PLANT4_KEY],
        ["images/parts/tree.png", MapObjectKey.MAP_TREE_KEY],
        ["images/parts/tree2.png", MapObjectKey.MAP_TREE2_KEY],
        ["images/parts/tree3.png", MapObjectKey.MAP_TREE3_KEY],
        ["images/parts/florite.png", MapObjectKey.MAP_FLORITE_KEY],
        ["images/parts/campfire.png", MapObjectKey.MAP_CAMPFIRE_KEY],
        ["images/parts/door_closed.png", MapObjectKey.MAP_DOOR_CLOSED_KEY],
        ["images/parts/door_open.png", MapObjectKey.MAP_DOOR_OPEN_KEY],
        ["images/parts/door_closed2.png", MapObjectKey.MAP_DOOR_CLOSED2_KEY],
        ["images/parts/door_open2.png", MapObjectKey.MAP_DOOR_OPEN2_KEY],
        ["images/parts/torch.png", MapObjectKey.MAP_TORCH_KEY],
        ["images/parts/anvil.png", MapObjectKey.MAP_ANVIL_KEY],
        ["images/parts/smelter.png", MapObjectKey.MAP_SMELTER_KEY],
        ["images/parts/iron_ingot.png", MapObjectKey.MAP_IRON_INGOT_KEY],
        ["images/parts/iron_fence.png", MapObjectKey.MAP_IRON_FENCE_KEY],
        ["images/parts/fireplace.png", MapObjectKey.MAP_FIREPLACE_KEY]
    ];
}