namespace Lich {
    export let UI_DEFS: Array<[string, UISpriteKey]> = [
        ["ui_player_icon", UISpriteKey.UI_PLAYER_ICON_KEY],
        ["ui_skull", UISpriteKey.UI_SKULL_KEY],
        ["ui_dead_again", UISpriteKey.UI_GAME_OVER_KEY],
        ["ui_sound", UISpriteKey.UI_SOUND_KEY],
        ["ui_up", UISpriteKey.UI_UP_KEY],
        ["ui_down", UISpriteKey.UI_DOWN_KEY],
        ["ui_left", UISpriteKey.UI_LEFT_KEY],
        ["ui_right", UISpriteKey.UI_RIGHT_KEY],
        ["ui_left_up", UISpriteKey.UI_LEFT_UP_KEY],
        ["ui_right_up", UISpriteKey.UI_RIGHT_UP_KEY],
        ["ui_left_down", UISpriteKey.UI_LEFT_DOWN_KEY],
        ["ui_right_down", UISpriteKey.UI_RIGHT_DOWN_KEY],
        ["ui_craft", UISpriteKey.UI_CRAFT_KEY],
        ["ui_load", UISpriteKey.UI_LOAD_KEY],
        ["ui_save", UISpriteKey.UI_SAVE_KEY],
        ["ui_new_world", UISpriteKey.UI_NEW_WORLD_KEY],
        ["ui_help", UISpriteKey.UI_HELP_KEY],
        ["ui_backpack", UISpriteKey.UI_BACKPACK_KEY],
        ["ui_menu", UISpriteKey.UI_MENU_KEY],
        ["ui_minimap", UISpriteKey.UI_MINIMAP_KEY],
    ]

    export let FONT_DEFS: Array<[FontKey, [string, string]]> = [
        [FontKey.FNT_SMALL_YELLOW_KEY,
        ['a', 'small_yellow_a'],
        ['b', 'small_yellow_b'],
        ['c', 'small_yellow_c'],
        ['d', 'small_yellow_d'],
        ['e', 'small_yellow_e'],
        ['f', 'small_yellow_f'],
        ['g', 'small_yellow_g'],
        ['h', 'small_yellow_h'],
        ['i', 'small_yellow_i'],
        ['j', 'small_yellow_j'],
        ['k', 'small_yellow_k'],
        ['l', 'small_yellow_l'],
        ['m', 'small_yellow_m'],
        ['n', 'small_yellow_n'],
        ['o', 'small_yellow_o'],
        ['p', 'small_yellow_p'],
        ['q', 'small_yellow_q'],
        ['r', 'small_yellow_r'],
        ['s', 'small_yellow_s'],
        ['t', 'small_yellow_t'],
        ['u', 'small_yellow_u'],
        ['v', 'small_yellow_v'],
        ['w', 'small_yellow_w'],
        ['x', 'small_yellow_x'],
        ['y', 'small_yellow_y'],
        ['z', 'small_yellow_z'],
        ['%', 'small_yellow_percent'],
        ['!', 'small_yellow_excl'],
        ['?', 'small_yellow_question'],
        [';', 'small_yellow_semicolon'],
        [':', 'small_yellow_colon'],
        [',', 'small_yellow_comma'],
        ['"', 'small_yellow_quote'],
        ['\'', 'small_yellow_apostrophe'],
        ['.', 'small_yellow_dot'],
        ['+', 'small_yellow_plus'],
        ['-', 'small_yellow_minus'],
        ['/', 'small_yellow_slash'],
        ['*', 'small_yellow_star'],
        ['=', 'small_yellow_eq'],
        ['←', 'small_yellow_left'],
        ['→', 'small_yellow_right'],
        ['<', 'small_yellow_lt'],
        ['>', 'small_yellow_gt'],
        ['(', 'small_yellow_left_bracket'],
        [')', 'small_yellow_right_bracket'],
        ['0', 'small_yellow_0'],
        ['1', 'small_yellow_1'],
        ['2', 'small_yellow_2'],
        ['3', 'small_yellow_3'],
        ['4', 'small_yellow_4'],
        ['5', 'small_yellow_5'],
        ['6', 'small_yellow_6'],
        ['7', 'small_yellow_7'],
        ['8', 'small_yellow_8'],
        ['9', 'small_yellow_9']
        ]
    ]
}