namespace Lich {
    export let UI_DEFS: Array<[string, UISpriteKey]> = [
        ["ui_player_icon", UISpriteKey.UI_PLAYER_ICON_KEY],
        ["ui_skull", UISpriteKey.UI_SKULL_KEY],
        ["ui_dead_again", UISpriteKey.UI_GAME_OVER_KEY],
        ["ui_sound", UISpriteKey.UI_SOUND_KEY],
        ["ui_up", UISpriteKey.UI_UP_KEY],
        ["ui_down", UISpriteKey.UI_DOWN_KEY],
        ["ui_left", UISpriteKey.UI_LEFT_KEY],
        ["ui_right", UISpriteKey.UI_RIGHT_KEY],
        ["ui_left_up", UISpriteKey.UI_LEFT_UP_KEY],
        ["ui_right_up", UISpriteKey.UI_RIGHT_UP_KEY],
        ["ui_left_down", UISpriteKey.UI_LEFT_DOWN_KEY],
        ["ui_right_down", UISpriteKey.UI_RIGHT_DOWN_KEY],
        ["ui_craft", UISpriteKey.UI_CRAFT_KEY],
        ["ui_load", UISpriteKey.UI_LOAD_KEY],
        ["ui_save", UISpriteKey.UI_SAVE_KEY],
        ["ui_new_world", UISpriteKey.UI_NEW_WORLD_KEY],
        ["ui_help", UISpriteKey.UI_HELP_KEY],
        ["ui_backpack", UISpriteKey.UI_BACKPACK_KEY],
        ["ui_menu", UISpriteKey.UI_MENU_KEY],
        ["ui_minimap", UISpriteKey.UI_MINIMAP_KEY],
        ["ui_highlight", UISpriteKey.UI_HIGHLIGHT_KEY],
        ["ui_panel_middle", UISpriteKey.UI_PANEL_MIDDLE_KEY],
        ["ui_panel_top", UISpriteKey.UI_PANEL_TOP_KEY],
        ["ui_panel_right", UISpriteKey.UI_PANEL_RIGHT_KEY],
        ["ui_panel_bottom", UISpriteKey.UI_PANEL_BOTTOM_KEY],
        ["ui_panel_left", UISpriteKey.UI_PANEL_LEFT_KEY],
        ["ui_panel_tl", UISpriteKey.UI_PANEL_TL_KEY],
        ["ui_panel_tr", UISpriteKey.UI_PANEL_TR_KEY],
        ["ui_panel_br", UISpriteKey.UI_PANEL_BR_KEY],
        ["ui_panel_bl", UISpriteKey.UI_PANEL_BL_KEY],
        ["ui_button", UISpriteKey.UI_BUTTON_KEY],
        ["ui_fireball_spell", UISpriteKey.UI_FIREBALL_KEY],
        ["ui_meteor_spell", UISpriteKey.UI_METEOR_KEY],
        ["ui_loveletter_spell", UISpriteKey.UI_LOVELETTER_KEY],
        ["ui_lovearrow_spell", UISpriteKey.UI_LOVEARROW_KEY],
        ["ui_bolt_spell", UISpriteKey.UI_ICEBOLT_KEY],
        ["ui_use_spell", UISpriteKey.UI_USE_ITEM_KEY],
        ["ui_place_spell", UISpriteKey.UI_REVEAL_FOG_KEY],
        ["ui_teleport_spell", UISpriteKey.UI_TELEPORT_KEY],
        ["ui_home_spell", UISpriteKey.UI_HOME_KEY],
        ["ui_place_spell", UISpriteKey.UI_INTERACT_KEY],
        ["ui_dig_spell", UISpriteKey.UI_DIG_KEY],
        ["ui_dig_bgr_spell", UISpriteKey.UI_DIG_BGR_KEY],
        ["ui_place_spell", UISpriteKey.UI_PLACE_KEY],
        ["ui_place_bgr_spell", UISpriteKey.UI_PLACE_BGR_KEY],
        ["ui_enemy_spell", UISpriteKey.UI_ENEMY_KEY]
    ]

    export let FONT_DEFS: Array<[FontKey, [[string, string]]]> = [
        [FontKey.FNT_SMALL_YELLOW_KEY, [
            ['0', 'fnt_small_yellow_0'],
            ['1', 'fnt_small_yellow_1'],
            ['2', 'fnt_small_yellow_2'],
            ['3', 'fnt_small_yellow_3'],
            ['4', 'fnt_small_yellow_4'],
            ['5', 'fnt_small_yellow_5'],
            ['6', 'fnt_small_yellow_6'],
            ['7', 'fnt_small_yellow_7'],
            ['8', 'fnt_small_yellow_8'],
            ['9', 'fnt_small_yellow_9'],
            ['a', 'fnt_small_yellow_a'],
            ['b', 'fnt_small_yellow_b'],
            ['c', 'fnt_small_yellow_c'],
            ['d', 'fnt_small_yellow_d'],
            ['e', 'fnt_small_yellow_e'],
            ['f', 'fnt_small_yellow_f'],
            ['g', 'fnt_small_yellow_g'],
            ['h', 'fnt_small_yellow_h'],
            ['i', 'fnt_small_yellow_i'],
            ['j', 'fnt_small_yellow_j'],
            ['k', 'fnt_small_yellow_k'],
            ['l', 'fnt_small_yellow_l'],
            ['m', 'fnt_small_yellow_m'],
            ['n', 'fnt_small_yellow_n'],
            ['o', 'fnt_small_yellow_o'],
            ['p', 'fnt_small_yellow_p'],
            ['q', 'fnt_small_yellow_q'],
            ['r', 'fnt_small_yellow_r'],
            ['s', 'fnt_small_yellow_s'],
            ['t', 'fnt_small_yellow_t'],
            ['u', 'fnt_small_yellow_u'],
            ['v', 'fnt_small_yellow_v'],
            ['w', 'fnt_small_yellow_w'],
            ['x', 'fnt_small_yellow_x'],
            ['y', 'fnt_small_yellow_y'],
            ['z', 'fnt_small_yellow_z'],
            ['\'', 'fnt_small_yellow_apostrophe'],
            [':', 'fnt_small_yellow_colon'],
            [',', 'fnt_small_yellow_comma'],
            ['.', 'fnt_small_yellow_dot'],
            ['=', 'fnt_small_yellow_eq'],
            ['!', 'fnt_small_yellow_excl_mark'],
            ['>', 'fnt_small_yellow_gt'],
            // ['←', 'fnt_small_yellow_left'],
            ['(', 'fnt_small_yellow_left_bracket'],
            ['<', 'fnt_small_yellow_lt'],
            ['-', 'fnt_small_yellow_minus'],
            ['%', 'fnt_small_yellow_percent'],
            ['+', 'fnt_small_yellow_plus'],
            ['?', 'fnt_small_yellow_question_mark'],
            ['"', 'fnt_small_yellow_quote'],
            // ['→', 'fnt_small_yellow_right'],
            [')', 'fnt_small_yellow_right_bracket'],
            ['/', 'fnt_small_yellow_slash'],
            ['*', 'fnt_small_yellow_star'],
            [';', 'fnt_small_yellow_semicolon']
        ]
        ]
    ]
}